{% set name = "mofdscribe" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mofdscribe-{{ version }}.tar.gz
  sha256: 4a7f4b05a705fa1c6c5cb35b79597e12b75105cb52150a2bdfe4e8e1fa2cf371

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matminer
    - loguru
    - pystow
    - ase
    - structuregraph-helpers
    - element-coder
    - pydantic
    - typing-extensions
    - openbabel
    - raspa2
    - zeopp-lsmo
    - moleculetda
    - rdkit

test:
  imports:
    - mofdscribe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kjappelbaum/mofdscribe
  summary: Ecosystem for digital reticular chemistry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
